import type { Metadata } from "next";
import "./globals.css";
import styles from "./page.module.css";
import Image from "next/image";
import github from "./images/github.png";


export const metadata: Metadata = {
  title: "Judah Christman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <div>
          <p className={styles.bottomText}>Judah Christman 2025</p>
          <div className={styles.social}>
            <a className={styles.socialLinks}>
              <Image
                src={github}
                width={30}
                height={30}
                alt="github"
              />
            </a>
          </div>
        </div>
      </body>
    </html>
  );
}
