import type { Metadata } from "next";
import "./globals.css";
import {motion } from "framer-motion";
import Image from "next/image";
import Link from "next/link";
import github from "./images/github.png";
import { Navigation } from "./components.jsx";
import { SpeedInsights } from "@vercel/speed-insights/next";


export const metadata: Metadata = {
  title: "Judah Christman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <div className="w-full p-2 relative bg-green-300 flex justify-between">
          <p className="">Judah Christman 2025</p>
            <a href="https://github.com/Judah-Christman" target="_blank">
              <Image
                src={github}
                width={30}
                height={30}
                style={{ position: "absolute", right: "5px" }}
                alt="github"
              />
            </a>
        </div>
      </body>
    </html>
  );
}
